### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Bima42** [tyrossel/webserv#48]
## TO IMPLEMENT
- [x] : Verbose mode clean
- [x] : remove -g in Makefile
- [x] : update status in Request.cpp when Method is not allowed and when body is too long (call in Looper l.169)
- [x] : check ALL TODO in code
- [x] : Looper l.430 -> Default switch should be crafting error page with METHOD_NOT_IMPLEMENTED error
- [x] : FIX findServer and findLoc if no serv or no loc are found !
- [x] : Change the log for buildRedirectionResponse
### PARSING
- [x] : Custom error pages

### EXECUTION
- [x] : Craft DELETE method
- [x] : Create loop for reading client request
- [x] : Connect CGI to execution part using Location for cgi-path 
- [x] : Autoindex
- [x] : Connect directory listing to execution
- [x] : Craft a default error in string object instead of find a 404_pages in case of this file does not exist
- [x] : HTTP Redirection

### CHECKING
- [x] : Protect from client-max-body-size
- [x] : Matching Server before matching Location
- [x] : If cgi-exe path is good and the file exist
- [x] : Check the return value of each recv/read/send/write and handle errors (c.f. correction)
- [x] : Wrong address should not start our server (OK: bind error, mais exit pas)

### Looper
- [x] : Review all errors checking for POST and DELETE
- [x] : Update path after parsing request to append the full path
- [x] : update operator =

### CGI
- [x] : Check if execve failed and exit correctly according to this fail 
- [x] : Protect from GET request without body
- [x] : Update cgi execution

### RequestParser
- [x] : Break RequestParser in two part 
  - RequestParser only for parsing client request
  - Request holding the request and attributs checking functions etc
- [x] : RequestType should be attribut of RequestParser
- [x] : Move checking allowed methods from Looper to RequestParser

### Looper
- [x] : Clean Looper object 
  - Change some function parameters 
- [x] : Move buildResponse part in another object called Response
  - [x] : Status of CGI return should be inside of Response object, because when cgi failed we have to check the new status 
- [x] : Remove return -1 from readFromClient. When error is caught, we have to build errorResponse and continue server
- [x] : Behavior of Looper when recv return -1 is really stranged try to  know why

### Location
- [x] Replace allowed_method type from `int` to `std::bitfield`

### Response
- [x] : add a status in private member

### Architecture
- [x] : root repository should be outside of src
- [x] : rename all variables for more sense, logic

## BONUS
- [x] : Create script to link with button in HTML
- [x] : Insert php script to stock POST request in JSON file
- [x] : Create HTML page with all methods to make tests easier for evaluation
- [x] : Also for eval: some bash script for tests with `siege` and `curl`
- [x] : README docs

## Security
- [x] : Limit the size of request headers: drop connection if too long (or send bad request back)

**Comment by tyrossel** [comment]
So, can we close this ?
