### ISSUE TITLE
Roadmap: who does what ?

### ISSUE THREAD

**Issue by tyrossel** [tyrossel/webserv#7]
- [x] #9
  - [x] Creation of `Config` object
- [x] #8
- [x] #15
- [x] #16
- [x] #17
   - [x] : First line
   - [x] : Headers
   - [x] : Body
   - [x] : Query string in path
   - [x] : Chunked-Body  
- [x] #20
- [x] #28
   - [x] : check if each server is set correctly
- [x] #29
  - [x] Find the correct server
  - [x] For each location, try to match request to location_path
  - [x] If it's a CGI/proxy location, send it forward to it. 
  - [x] If not, find the document in the root and send it back to the client
- [x] [loop] Manage signals
- [x] #31
- [x] #32
- [x] Finish TODO List
